name: CaptureTheFlag
version: '${project.version}'
main: org.pippeloo.capturetheflag.CaptureTheFlag
api-version: '1.20'

commands:
  hub:
    description: Teleport to the hub
    usage: /<command>
    permission: ctf.hub
  sethub:
    description: Set the hub
    usage: /<command>
    permission: ctf.sethub
  ctf:
    arguments:
      setBlueSpawn:
        description: Set the blue spawn
        usage: /<command> setBlueSpawn
        permission: ctf.setBlueSpawn
      setRedSpawn:
        description: Set the red spawn
        usage: /<command> setRedSpawn
        permission: ctf.setRedSpawn