name: CaptureTheFlag
version: '${project.version}'
main: org.pippeloo.capturetheflag.CaptureTheFlag
api-version: '1.20'

commands:
  hub:
    description: Teleport to the hub
    usage: /<command>
    permission: ctf.hub
  sethub:
    description: Set the hub
    usage: /<command>
    permission: ctf.sethub
  ctf:
    description: Capture the flag commands
    usage: /<command> <setSpawn|setFlag|setEntrance>
    permission: ctf.ctf
    arguments:
      setSpawn:
        description: Set the team spawn
        usage: /<command> setSpawn <team>
        permission: ctf.setspawn
      setFlag:
        description: Set the team flag
        usage: /<command> setFlag <team>
        permission: ctf.setflag
      setEntrance:
        description: Set the team entrance
        usage: /<command> setEntrance <team>
        permission: ctf.setentrance

